name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: workspace-lint
        run: npx nx workspace-lint

      - name: format:check
        run: npx nx format:check

      - name: lint
        run: npx nx affected --target=lint --parallel=3

      - name: test
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage

      - name: build
        run: npx nx affected --target=build --parallel=3
